### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by KamuraGTR** [DeeSEmu/DeeS#2]
App Crashed on Android 6.0 Marshmallow
The app crashes when starting it

Cellphone: HTC One M9+
CPU: MediaTek Helio X10 Octacore 2.0GHz
RAM: 3GB

**Comment by official-antique** [comment]
Hey @KamuraGTR, are you able to retrieve a crash log at all? I'm unsure how to do it on Android but if you could that would help immensely!

**Comment by KamuraGTR** [comment]
@official-antique I didn't found the crash log
App show a window "Unfortunately, the app has stopped"
App don't let me starting

**Comment by KamuraGTR** [comment]
Sorry, accidentally I touch close issue 😅

Well, I'll try to find the crash log and later send it here

**Comment by KamuraGTR** [comment]
![Screenshot_20230129-104125](https://user-images.githubusercontent.com/123827309/215337737-d8be7118-f84c-4d27-b046-8219145c0544.png)

**Comment by Gamemulatorer** [comment]
Here's some crash log
```
ComposableLambda.jvm.kt:107)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3314)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3304)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3304)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3239)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:967)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1089)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1176)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:20704)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3541)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2708)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2214)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8686)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:779)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:257)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8218)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
03-20 23:29:28.705 14187 14187 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
03-20 23:29:29.620 14236 14236 D AndroidRuntime: Shutting down VM
03-20 23:29:29.621 14236 14236 E AndroidRuntime: FATAL EXCEPTION: main
03-20 23:29:29.621 14236 14236 E AndroidRuntime: Process: com.antique.dees, PID: 14236
03-20 23:29:29.621 14236 14236 E AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x106002b
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:295)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.content.res.Resources.getColor(Resources.java:1147)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.graphics.Api26Bitmap$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.material3.ColorResourceHelper.getColor-WaAFU9c(DynamicTonalPalette.kt:186)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.material3.DynamicTonalPaletteKt.dynamicTonalPalette(DynamicTonalPalette.kt:47)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.material3.DynamicTonalPaletteKt.dynamicLightColorScheme(DynamicTonalPalette.kt:117)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at com.antique.dees.ui.theme.ThemeKt.DeeSTheme(Theme.kt:49)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at com.antique.dees.GameBrowser$onCreate$1.invoke(GameBrowser.kt:62)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at com.antique.dees.GameBrowser$onCreate$1.invoke(GameBrowser.kt:61)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3314)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3304)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3304)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3239)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:967)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1089)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1176)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:20704)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3541)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3548)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2708)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2214)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8686)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:779)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:257)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8218)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
03-20 23:29:29.621 14236 14236 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
```
